backend/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('signup/sent/', views.activation_sent_view, name='activation_sent'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('require_email/', views.require_email_view, name='require_email'),

    path('login/', views.login_view, name='login'),

    path('logout/', views.logout_view, name='logout'),
]

backend/follow/urls.py
from django.urls import path
from .views import follow_toggle_ajax, followers_list, following_list

app_name = 'follow'

urlpatterns = [
    path('toggle/<str:username>/', follow_toggle_ajax, name='toggle-ajax'),
    path('followers/<str:username>/', followers_list, name='followers'),
    path('following/<str:username>/', following_list, name='following'),
]

backend/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('user/', include('user.urls', namespace='user')),
    path('posts/', include("posts.urls")),
    path('follow/', include('follow.urls', namespace='follow')),
    path('auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
   urlpatterns += static(
       settings.STATIC_URL,
       document_root=settings.STATICFILES_DIRS[0]
   )

urlpatterns += static(
     settings.MEDIA_URL,
     document_root=settings.MEDIA_ROOT
)

backend/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('edit/', views.edit_profile_view, name='edit_profile'),
    path('<str:username>/', views.profile_view, name='profile'),
]

backend/user/models.py
from django.db import models
from django.conf import settings
from django.templatetags.static import static
from cloudinary.models import CloudinaryField



class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    avatar = CloudinaryField('avatar')
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateTimeField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    @property
    def avatar_url(self):
        if self.avatar and hasattr(self.avatar, 'public_id'):
            return self.avatar.build_url(width=150, height=150, crop='thumb', gravity='face')
        return static('img/default_avatar.jpg')


    def __str__(self):
        return f"{self.user.username}'s Profile"

backend/user/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'bio', 'location', 'birth_date']
        widgets = {
            'birth_date': forms.DateInput(attrs={'type': 'date'}),
        }

backend/user/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user_model

from .forms import ProfileForm
from .models import Profile


User = get_user_model()


def profile_view(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    return render(request, 'user/profile.html',
                  {'profile': profile, 'profile_user':profile.user})


@login_required
def edit_profile_view(request):
    profile = get_object_or_404(Profile, user=request.user)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('user:profile', username=request.user.username)
    else:
        form = ProfileForm(instance=profile)

    return render(request, 'user/edit_profile.html', {'form': form, 'profile':profile})

backend/user/templates/user/edit_profile.html
{% extends "base.html" %}
{% load cloudinary %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
<div class="form-container mx-auto mt-5" style="max-width: 500px;">
    <h3 class="text-center mb-4">Edit Profile</h3>

    <form method="POST" enctype="multipart/form-data" novalidate>
        {% csrf_token %}

        <div class="text-center mb-3">

<img src="{{ profile.avatar_url }}"
     class="rounded-circle"
     alt="Аватар профілю"
     style="width: 150px; height: 150px; object-fit: cover;">

            <br>
            <label for="id_avatar" class="btn btn-outline-secondary btn-sm">Change Profile Photo</label>
            {{ form.avatar }}
        </div>

        <div class="mb-3">
            {{ form.bio.label_tag }}
            {% render_field form.bio class="form-control" placeholder="Your bio" %}
        </div>

        <div class="mb-3">
            {{ form.location.label_tag }}
            {% render_field form.location class="form-control" placeholder="Your location" %}
        </div>

        <div class="mb-3">
            {{ form.birth_date.label_tag }}
            {% render_field form.birth_date class="form-control" type="date" %}
        </div>

        <button type="submit" class="btn btn-primary w-100">Save Changes</button>
    </form>
</div>

<style>
    #id_avatar {
        display: none;
    }
</style>
{% endblock %}

backend/user/templates/user/profile.html
{% extends "base.html" %}
{% load static %}
{% load follow_tags %}
{% load cloudinary %}
{% block content %}
<div class="container text-center">

<img src="{{ profile.avatar_url }}"
     class="rounded-circle"
     alt="Аватар профілю"
     style="width: 150px; height: 150px; object-fit: cover;">

  <h2>{{ profile.user.username }}</h2>
  <p>{{ profile.bio }}</p>

  {% if request.user == profile.user %}
  <div class="d-flex justify-content-center gap-4 mb-4">
    <a href="{% url 'follow:followers' profile.user.username %}" class="text-decoration-none">
      <strong class="followers-count">{{ profile.user.followers_set.count }}</strong> Followers
    </a>

  <a href="{% url 'follow:following' profile.user.username %}"
     class="text-decoration-none">
    <strong>{{ profile.user.following_set.count }}</strong> Following
  </a>
</div>


    <a href="{% url 'user:edit_profile' %}"
       class="btn btn-primary mt-3">
      Edit Profile
    </a>
    <a href="{% url 'accounts:logout' %}"
       class="btn btn-outline-danger mt-3">
      Logout
    </a>
  {% else %}
    <div class="d-flex align-items-center justify-content-center mt-3">
      {% follow_button profile.user %}
    </div>
  {% endif %}
</div>
{% endblock %}