backend/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path("", views.home_view, name="home"),
    path('feed/', views.feed_view, name='feed'),
    path("create/", views.create_post, name='create'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:pk>/like-ajax/', views.like_post_ajax, name='like-ajax'),
]

backend/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('user/', include('user.urls', namespace='user')),
    path('posts/', include("posts.urls")),
    path('follow/', include('follow.urls', namespace='follow')),
    path('auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
   urlpatterns += static(
       settings.STATIC_URL,
       document_root=settings.STATICFILES_DIRS[0]
   )

urlpatterns += static(
     settings.MEDIA_URL,
     document_root=settings.MEDIA_ROOT
)

backend/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('edit/', views.edit_profile_view, name='edit_profile'),
    path('<str:username>/', views.profile_view, name='profile'),
]

backend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}My App{% endblock %}</title>


  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
    rel="stylesheet"
  >


  <link rel="stylesheet" href="{% static 'css/styles.css' %}">



  <link rel="icon" href="{% static 'img/favicon/favicon.png' %}">

</head>
<body>
  {% if request.user.is_authenticated %}
  <div class="sidebar d-flex flex-column align-items-start p-3">
    <a href="{% url 'posts:home' %}" class="nav-link">
      <i class="bi bi-house-door"></i> Головна
    </a>
    <a href="{% url 'posts:feed' %}" class="nav-link">
    <i class="bi bi-stream"></i> Feed
    </a>
    <a href="#" class="nav-link">
      <i class="bi bi-search"></i> Пошук
    </a>
    <a href="#" class="nav-link">
      <i class="bi bi-compass"></i> Цікаве
    </a>
    <a href="#" class="nav-link">
      <i class="bi bi-camera-reels"></i> Reels
    </a>
    <a href="#" class="nav-link">
      <i class="bi bi-chat-dots"></i> Повідомлення
    </a>
    <a href="#" class="nav-link">
      <i class="bi bi-heart"></i> Сповіщення
    </a>
    <a href="{% url 'posts:create' %}" class="nav-link">
      <i class="bi bi-plus-square"></i> Створити
    </a>
    <a
      href="{% url 'user:profile' username=request.user.username %}"
      class="nav-link d-flex align-items-center"
    >
      <img
        src="{{ request.user.profile.avatar_url }}"
        class="rounded-circle sidebar-avatar me-2"
        alt="Avatar"
      >
      Профіль
    </a>
    <hr class="w-100">
    <a href="#" class="nav-link">
      <i class="bi bi-threads"></i> Threads
    </a>
    <a href="#" class="nav-link">
      <i class="bi bi-list"></i> Більше
    </a>
  </div>
  {% endif %}
  <!-- Main content -->
  <div class="container main-content">
    {% if messages %}
      {% for message in messages %}
        <div
          class="alert alert-{{ message.tags }} alert-dismissible fade show"
          role="alert"
        >
          {{ message }}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
      {% endfor %}
    {% endif %}

    {% block content %}{% endblock %}
  </div>


  <script src="{% static 'js/bundle.js' %}"></script>
</body>
</html>